### ISSUE TITLE
Cannot get `/api/version`

### ISSUE THREAD

**Issue by Silex** [reyzzz/quasaScale-backend#7]
Can you help me debug this?

```
# Request OK
curl -X 'GET' -H 'Authorization: Bearer xxx'  'https://backend.connect.mydomain.com/api/nodes'   -H 'accept: application/json'
[{"id":1,"name":"somehostname","ipv4":"1...

# Backend logs OK
quasascale-backend-1  | <-- GET /api/nodes
quasascale-backend-1  | --> GET /api/nodes 200 166ms

# Request FAIL
curl -X 'GET' -H 'Authorization: Bearer xxx'  'https://backend.connect.mydomain.com/api/version'   -H 'accept: application/json'
Internal Server Error

# Backend logs FAIL
quasascale-backend-1  | <-- GET /api/version
quasascale-backend-1  |  7 |   class ShellError extends Error {
quasascale-backend-1  |  8 |     #output = @undefined;
quasascale-backend-1  |  9 |     info;
quasascale-backend-1  | 10 |     exitCode;
quasascale-backend-1  | 11 |     stdout;
quasascale-backend-1  | 12 |     constructor() {
quasascale-backend-1  |                     ^
quasascale-backend-1  | ShellError: Failed with exit code 1
quasascale-backend-1  |  info: {
quasascale-backend-1  |   "exitCode": 1,
quasascale-backend-1  |   "stderr": "",
quasascale-backend-1  |   "stdout": ""
quasascale-backend-1  | }
quasascale-backend-1  |
quasascale-backend-1  |       at new ShellError (12:16)
quasascale-backend-1  |       at new ShellPromise (72:16)
quasascale-backend-1  |       at BunShell (188:35)
quasascale-backend-1  |       at /usr/src/app/index.js:13:44140
quasascale-backend-1  |       at version (/usr/src/app/index.js:13:44210)
quasascale-backend-1  |       at /usr/src/app/index.js:13:46381
quasascale-backend-1  |       at version (/usr/src/app/index.js:13:46384)
quasascale-backend-1  |       at /usr/src/app/index.js:16:2364
quasascale-backend-1  |       at /usr/src/app/index.js:16:2388
quasascale-backend-1  |       at /usr/src/app/index.js:12:9616
quasascale-backend-1  |
quasascale-backend-1  | --> GET /api/version 500 4ms
```

**Comment by Silex** [comment]
Ok, seems to be related to https://github.com/reyzzz/quasaScale-backend/blob/main/src/engine/DockerEngine.ts#L70

Probably simply that my bun container does not have the docker binary.

**Comment by Silex** [comment]
Ok I managed to repair the docker issue, now the problem is that the CORS header is only set on the `/api` path and thus quasascale fails to load:

```
philippe@mydomain-pv-laptop-01:~/work/headscale$ curl -v -X 'GET' -H 'Authorization: Bearer xxx'  'http://connect.mydomain.com:8000/version'   -H 'accept: application/json' 2>&1
*   Trying 116.203.139.38:8000...
* Connected to connect.mydomain.com (116.203.139.38) port 8000 (#0)
> GET /version HTTP/1.1
> Host: connect.mydomain.com:8000
> User-Agent: curl/7.81.0
> Authorization: Bearer dxwl3RGWLQ.f6OKFDWGi1wL9fUT1UosQS_mEkqmj4xSf1ggD4M9pLU
> accept: application/json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=UTF-8
< Date: Mon, 02 Dec 2024 13:47:37 GMT
< Content-Length: 13
<
* Connection #0 to host connect.mydomain.com left intact
404 Not Foundphilippe@mydomain-pv-laptop-01:~/work/headscale$

philippe@mydomain-pv-laptop-01:~/work/headscale$ curl -v -X 'GET' -H 'Authorization: Bearer xxx'  'http://connect.mydomain.com:8000/api/version'   -H 'accept: application/json' 2>&1
*   Trying 116.203.139.38:8000...
* Connected to connect.mydomain.com (116.203.139.38) port 8000 (#0)
> GET /api/version HTTP/1.1
> Host: connect.mydomain.com:8000
> User-Agent: curl/7.81.0
> Authorization: Bearer dxwl3RGWLQ.f6OKFDWGi1wL9fUT1UosQS_mEkqmj4xSf1ggD4M9pLU
> accept: application/json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Access-Control-Allow-Origin: https://quasa.connect.mydomain.com
< Vary: Origin
< Date: Mon, 02 Dec 2024 13:47:43 GMT
< Content-Length: 21
<
* Connection #0 to host connect.mydomain.com left intact
{"version":"v0.23.0"}
```

As you see, `Access-Control-Allow-Origin:` is only set if I query `/api`, but quasascale asks for `/version`. Please advice.

Just so you understand, I have backend.connect.mydomain.com that maps to quasascale-backend, quasa.connect.mydomain.com that maps to quasascale, and connect.mydomain.com maps to headscale.

**Comment by Silex** [comment]
Holy cow!

> QuasaScale Backend url ending with /api. e.g. https://quasascale-backend.io/api

Now it works :-)
